apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: grafana-image-render
    app.kubernetes.io/name: image-render
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 8.3.3
  name: image-render
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: http
    port: 8081
    nodePort: 32325
  selector:
    app.kubernetes.io/component: grafana-image-render
    app.kubernetes.io/name: image-render
    app.kubernetes.io/part-of: kube-prometheus