apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: image-render
  name: image-render
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-render
  strategy: {}
  template:
    metadata:
      labels:
        app: image-render
        app.kubernetes.io/component: grafana-image-render
        app.kubernetes.io/name: image-render
        app.kubernetes.io/part-of: kube-prometheus
    spec:
      containers:
      - env:
        - name: HTTP_PORT
          value: "8081"
        - name: HTTP_HOST
          value: 0.0.0.0
        - name: ENABLE_METRICS
          value: "true"
        - name: GRAFANA_MAGE_RENDERER_PORT
          value: "tcp://localhost:8081"
        - name: GRAFANA_IMAGE_RENDERER_PORT_8081_TCP_ADDR
          value: "localhost"
        - name: GRAFANA_IMAGE_RENDERER_PORT_8081_TCP_PROTO
          value: "tcp"
        - name: GRAFANA_IMAGE_RENDERER_SERVICE_PORT_HTTP
          value: "8081"
        - name: GRAFANA_MAGE_RENDERER_SERVICE_HOST
          value: "localohost"
        - name: GRAFANA_IMAGE_RENDERER_PORT_8081_TCP_PORT
          value: "8081"
        - name: GRAFANA_IMAGE_RENDERER_PORT_8081_TCP
          value: "tcp://localhost:8081"
        - name: GRAFANA_IMAGE_RENDERER_SERVICE_PORT
          value: "8081"
        image: grafana/grafana-image-renderer:3.5.0
        name: grafana-image-renderer
        resources: {}
        ports:
        - containerPort: 8081