apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
      app: image-render
      app.kubernetes.io/component: grafana-image-render
      app.kubernetes.io/name: image-render
      app.kubernetes.io/part-of: kube-prometheus
  name: image-render
  namespace: monitoring